# -*- coding: utf-8 -*-
"""TM_FINAL.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AU8qn-3aPYhsd9zpWRT9-mYGrT4bgM35

<a href="https://colab.research.google.com/github/ierigeri/Practica-1/blob/Tranque-el-mauro/TM_FINAL.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## PyGMTSAR Time series: Tranque el Mauro, Chile

Breve introducción blabla

# Instalación de Google Colab

Instalaremos PyGMTSAR y los binarios requeridos de GMTSAR para que este software funcione (incluyendo SNAPHU, el cual es una herramienta complementaria usada específicamente para desenvolver fases interferométricas en imágenes de radar).
"""

# Commented out IPython magic to ensure Python compatibility.
# Importaremos las librerías necesarias y se verifica si el código se está
# ejecutando en Google Colab.

import platform, sys, os

if 'google.colab' in sys.modules:
# Instalación de la librería PyGMTSAR
  !{sys.executable} -m pip install -q pygmtsar 'scipy==1.11.4'
  # Instalación de dependencias binarias
  import importlib.resources as resources
  with resources.as_file(resources.files('pygmtsar.data') / 'google_colab.sh') as google_colab_script_filename:
      !sh {google_colab_script_filename}
  # Vamos a permitir la visualización interactiva de datos
  from google.colab import output
  output.enable_custom_widget_manager()
  # Se inicializa un espacio de memoria (buffer) que simula una pantalla, permitiendo realizar operaciones gráficas 3D
  import xvfbwrapper
  display = xvfbwrapper.Xvfb(width=800, height=600)
  display.start()

# Configuramos la variable de entorno PATH para que incluya la ruta de instalación de GMTSAR
PATH = os.environ['PATH']
if PATH.find('GMTSAR') == -1:
    PATH = os.environ['PATH'] + ':/usr/local/GMTSAR/bin/'
#     %env PATH {PATH}

# Se imprime la versión de PyGMTSAR que se ha instalado.
from pygmtsar import __version__
__version__

"""# Cargar y configurar módulos de Python"""

# Se utiliza para trabajar con datos multidimensionales, como los datos de SAR.
import xarray as xr

# Permite trabajar con matrices y operaciones numéricas.
import numpy as np

# Se utiliza para manipular y analizar datos tabulares.
import pandas as pd

# Se utiliza para trabajar datos geoespaciales.
import geopandas as gpd

# Se usa comúnmente para almacenar y transferir datos.
import json

# Dask es ideal para trabajos que no caben en la memoria de un solo equipo.
from dask.distributed import Client

# Procesa grandes conjuntos de datos
import dask
import psutil

"""Esta parte del código se encarga de importar y configurar las librerías necesarias para la visualización de los datos. Se divide en dos partes importantes:

- Módulos de gráficos

"""

# define Pandas display settings/configura las opciones de visualización de Pandas
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)
pd.set_option('display.max_colwidth', 100)

# Commented out IPython magic to ensure Python compatibility.
# Módulos de gráficos

# Importa la librería de PyVista (pv), que se usa para la
# visualización 3D interactiva.
import pyvista as pv

# Configura el tema de PyVista a "document", que generalmente
# usa un fondo blanco para las gráficas.
pv.set_plot_theme("document")

# Importa la librería Panel, que se usa para crear paneles interactivos
# y visualizaciones web.
import panel

# Habilita la comunicación entre Panel y los widgets de Jupyter.
panel.extension(comms='ipywidgets')

# Habilita el soporte para visualizaciones VTK (Visualization Toolkit)
# en Panel, lo que permite integrar PyVista.
panel.extension('vtk')

# Importa contextmanager para manejar el contexto de la configuración de Matplotlib
from contextlib import contextmanager

# Importa la librería Matplotlib (plt), que se usa para crear gráficos estáticos.

import matplotlib.pyplot as plt

## Se define una función mpl_setting y configura los parámetros de Matplotlib


# Con esto se define el administrador de contexto, el cual controla lo que ocurre
# antes y después de ejecutar un bloque de código.
@contextmanager

# La función mpl_settings es un administrador de contexto, es decir, es una funcionalidad
# que permite ejecutar un bloque de código dentro de un entorno controlado. Este entorno
# generalmente asegura que se realicen ciertas acciones antes y después de ejecutar ese bloque
# de código, como configurar algo temporalmente y luego restaurarlo al finalizar. Lo que
# generará este administrador de contexto es que permitirá cambiar temporalmente la configuración
# de Matplotlib y luego restaurarla a su estado original.

def mpl_settings(settings):
    original_settings = {k: plt.rcParams[k] for k in settings}
    plt.rcParams.update(settings)
    yield
    plt.rcParams.update(original_settings)

plt.rcParams['figure.figsize'] = [12, 4]
plt.rcParams['figure.dpi'] = 150
plt.rcParams['figure.titlesize'] = 24
plt.rcParams['axes.titlesize'] = 14
plt.rcParams['axes.labelsize'] = 12
plt.rcParams['xtick.labelsize'] = 12
plt.rcParams['ytick.labelsize'] = 12
# %matplotlib inline

# Configura las opciones de visualización de Pandas
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)
pd.set_option('display.max_colwidth', 100)

# Se importan varias clases y funciones de la librería PyGMTSAR, que se usa para el
# procesamiento de datos de interferomoetría de radar de apertura sintética (InSAR).

from pygmtsar import S1, Stack, tqdm_dask, ASF, Tiles, XYZTiles

"""## Escenas SLC de Sentinel-1 y parámetros de procesamiento

### Descending Orbit Configuration

https://search.asf.alaska.edu/#/?zoom=12.378&center=-71.084,-31.998&polygon=POLYGON((-71.0863%20-32.0116,-70.9495%20-32.0116,-70.9495%20-31.9103,-71.0863%20-31.9103,-71.0863%20-32.0116))&start=2023-01-01T03:00:00Z&end=2024-01-02T02:59:59Z&flightDirs=Descending&resultsLoaded=true&granule=S1_334199_IW2_20231228T100423_VV_8714-BURST&maxResults=250&dataset=SENTINEL-1%20BURSTS&beamModes=IW&polarizations=VV
"""

# El subswath se utiliza exclusivamente cuando se necesitan descargar partes
# específicas de una escena, pero no es necesario cuando se descargan datos
# completos de una ráfaga. En cambio, la órbita sirve para establecer los nombres
# de los directorios donde se guardan los datos procesados
ORBIT    = 'D'
SUBSWATH = 2
REFERENCE = '2025-01-03'

BURSTS = """
S1_334199_IW2_20250103T100417_VV_5B3C-BURST
S1_334199_IW2_20241222T100418_VV_A3C9-BURST
S1_334199_IW2_20241210T100419_VV_0C53-BURST
S1_334199_IW2_20241128T100420_VV_6E43-BURST
S1_334199_IW2_20241116T100421_VV_3886-BURST
S1_334199_IW2_20241104T100421_VV_8550-BURST
S1_334199_IW2_20241011T100422_VV_66D7-BURST
S1_334199_IW2_20240929T100421_VV_82D6-BURST
S1_334199_IW2_20240917T100421_VV_C9CE-BURST
S1_334199_IW2_20240905T100420_VV_C923-BURST
S1_334199_IW2_20240824T100420_VV_1A2B-BURST
S1_334199_IW2_20240812T100420_VV_5399-BURST
S1_334199_IW2_20240731T100420_VV_1E9A-BURST
S1_334199_IW2_20240719T100420_VV_5954-BURST
S1_334199_IW2_20240707T100421_VV_29A7-BURST
S1_334199_IW2_20240625T100421_VV_51CC-BURST
S1_334199_IW2_20240613T100422_VV_B100-BURST
S1_334199_IW2_20240601T100422_VV_A18D-BURST
S1_334199_IW2_20240520T100422_VV_6DFB-BURST
S1_334199_IW2_20240508T100423_VV_74F6-BURST
S1_334199_IW2_20240426T100422_VV_AB5E-BURST
S1_334199_IW2_20240414T100421_VV_13EE-BURST
S1_334199_IW2_20240402T100422_VV_BE3F-BURST
S1_334199_IW2_20240321T100422_VV_D5C5-BURST
S1_334199_IW2_20240309T100421_VV_DFCD-BURST
S1_334199_IW2_20240226T100421_VV_A129-BURST
S1_334199_IW2_20240214T100421_VV_20D2-BURST
S1_334199_IW2_20240202T100421_VV_EBE9-BURST
S1_334199_IW2_20240121T100422_VV_D119-BURST
S1_334199_IW2_20240109T100422_VV_6DEE-BURST
S1_334199_IW2_20231228T100423_VV_8714-BURST
S1_334199_IW2_20231216T100424_VV_0864-BURST
S1_334199_IW2_20231204T100424_VV_FAD4-BURST
S1_334199_IW2_20231122T100425_VV_866A-BURST
S1_334199_IW2_20231110T100425_VV_8002-BURST
S1_334199_IW2_20231017T100425_VV_CE2D-BURST
S1_334199_IW2_20231005T100425_VV_44AC-BURST
S1_334199_IW2_20230923T100425_VV_4AAE-BURST
S1_334199_IW2_20230911T100425_VV_5ED7-BURST
S1_334199_IW2_20230830T100424_VV_22E8-BURST
S1_334199_IW2_20230818T100424_VV_EDA8-BURST
S1_334199_IW2_20230806T100423_VV_0B23-BURST
S1_334199_IW2_20230725T100422_VV_5BD3-BURST
S1_334199_IW2_20230713T100422_VV_93D6-BURST
S1_334199_IW2_20230701T100421_VV_D7E1-BURST
S1_334199_IW2_20230619T100420_VV_4380-BURST
S1_334199_IW2_20230607T100419_VV_4AEA-BURST
S1_334199_IW2_20230526T100419_VV_D912-BURST
S1_334199_IW2_20230514T100418_VV_C09B-BURST
S1_334199_IW2_20230502T100418_VV_399F-BURST
S1_334199_IW2_20230420T100416_VV_5A7B-BURST
S1_334199_IW2_20230408T100417_VV_E031-BURST
S1_334199_IW2_20230327T100416_VV_4FD3-BURST
S1_334199_IW2_20230315T100416_VV_37D9-BURST
S1_334199_IW2_20230303T100416_VV_7288-BURST
S1_334199_IW2_20230219T100416_VV_EB5A-BURST
S1_334199_IW2_20230207T100416_VV_2FB3-BURST
S1_334199_IW2_20230126T100417_VV_2D8C-BURST
S1_334199_IW2_20230114T100417_VV_47B3-BURST
S1_334199_IW2_20230102T100418_VV_552E-BURST
S1_334199_IW2_20221221T100418_VV_AE5C-BURST
S1_334199_IW2_20221209T100419_VV_B3BF-BURST
S1_334199_IW2_20221127T100420_VV_C13D-BURST
S1_334199_IW2_20221115T100420_VV_1A66-BURST
S1_334199_IW2_20221103T100420_VV_A286-BURST
S1_334199_IW2_20221022T100420_VV_467E-BURST
S1_334199_IW2_20221010T100420_VV_E783-BURST
S1_334199_IW2_20220928T100420_VV_1604-BURST
S1_334199_IW2_20220916T100420_VV_8BE6-BURST
S1_334199_IW2_20220904T100420_VV_1647-BURST
S1_334199_IW2_20220823T100419_VV_ECA8-BURST
S1_334199_IW2_20220811T100418_VV_0FDE-BURST
S1_334199_IW2_20220730T100418_VV_27A4-BURST
S1_334199_IW2_20220718T100417_VV_69F1-BURST
S1_334199_IW2_20220706T100416_VV_4CEA-BURST
S1_334199_IW2_20220624T100416_VV_14DB-BURST
S1_334199_IW2_20220612T100415_VV_6BC7-BURST
S1_334199_IW2_20220531T100414_VV_9DB0-BURST
S1_334199_IW2_20220519T100413_VV_F774-BURST
S1_334199_IW2_20220507T100412_VV_EFBB-BURST
S1_334199_IW2_20220413T100411_VV_7CA1-BURST
S1_334199_IW2_20211220T100331_VV_30AF-BURST
S1_334199_IW2_20211208T100331_VV_F993-BURST
S1_334199_IW2_20211126T100332_VV_E8AE-BURST
S1_334199_IW2_20211114T100332_VV_7D64-BURST
S1_334199_IW2_20211102T100332_VV_31FE-BURST
S1_334199_IW2_20211021T100333_VV_E2F4-BURST
S1_334199_IW2_20211009T100332_VV_F5A9-BURST
S1_334199_IW2_20210927T100332_VV_F81E-BURST
S1_334199_IW2_20210915T100332_VV_F1B0-BURST
S1_334199_IW2_20210903T100331_VV_F0A6-BURST
S1_334199_IW2_20210822T100331_VV_F18F-BURST
S1_334199_IW2_20210810T100330_VV_5CED-BURST
S1_334199_IW2_20210729T100330_VV_1169-BURST
S1_334199_IW2_20210717T100329_VV_065C-BURST
S1_334199_IW2_20210705T100328_VV_7712-BURST
S1_334199_IW2_20210623T100327_VV_2D6B-BURST
S1_334199_IW2_20210611T100327_VV_9DAA-BURST
S1_334199_IW2_20210530T100326_VV_DEE4-BURST
S1_334199_IW2_20210518T100325_VV_78B9-BURST
S1_334199_IW2_20210506T100325_VV_F2AF-BURST
S1_334199_IW2_20210424T100324_VV_4CEE-BURST
S1_334199_IW2_20210412T100323_VV_5ABB-BURST
S1_334199_IW2_20210331T100323_VV_7818-BURST
S1_334199_IW2_20210319T100323_VV_BF61-BURST
S1_334199_IW2_20210307T100323_VV_52CC-BURST
S1_334199_IW2_20210223T100323_VV_5F38-BURST
S1_334199_IW2_20210217T100405_VV_92EE-BURST
S1_334199_IW2_20210211T100323_VV_E213-BURST
S1_334199_IW2_20210130T100323_VV_B49C-BURST
S1_334199_IW2_20210118T100324_VV_1E45-BURST
S1_334199_IW2_20210106T100324_VV_7DC0-BURST
"""

BURSTS = list(filter(None, BURSTS.split('\n')))

print(f'Bursts defined: {len(BURSTS)}')

WORKDIR = 'raw_tranque_elmauro'  if ORBIT == 'D' else 'raw_tranque_elmauro'
DATADIR = 'data_tranque_elmauro' if ORBIT == 'D' else 'data_tranque_elmauro'

# define DEM and landmask filenames inside data directory
DEM = f'{DATADIR}/dem.nc'

geojson = '''
{
  "type": "Feature",
  "properties": {},
  "geometry": {
    "type": "Polygon",
    "coordinates": [
      [
      [-71.055, -31.9414],
      [-71.066, -31.9598],
      [-71.0476, -31.9816],
      [-71.0173, -31.9927],
      [-70.9905, -31.9828],
      [-70.9835, -31.9536],
      [-71.0012, -31.938],
      [-71.043, -31.9329],
      [-71.055, -31.9414]
      ]
    ]
  }
}
'''
AOI = gpd.GeoDataFrame.from_features([json.loads(geojson)])
AOI

BUFFER = 0.025

# Si la geometría definida es demasiado pequeña para que el procesamiento funcione
# correctamente se amplía la geometría para que cumpla con los requisitos mínimos del proceso.

AOI['geometry'] = AOI.buffer(BUFFER)

# Punto de deformación

geojson = '''
{
  "type": "Feature",
  "geometry": {
    "type": "Point",
    "coordinates": [-71.0389, -31.9559]
  },
  "properties": {}
}
'''
POI = gpd.GeoDataFrame.from_features([json.loads(geojson)])
POI

# Punto de referencia
geojson = '''
{
  "type": "Feature",
  "geometry": {
    "type": "Point",
    "coordinates": [-71.0542, -31.9490]
  },
  "properties": {}
}
'''
POI0 = gpd.GeoDataFrame.from_features([json.loads(geojson)])
POI0

"""## Download and Unpack Datasets

## Enter Your ASF User and Password

**Esta sección se encarga de obtener las imágenes Sentinel-1 necesarias para el análisis InSAR**

If the data directory is empty or doesn't exist, you'll need to download Sentinel-1 scenes from the Alaska Satellite Facility (ASF) datastore. Use your Earthdata Login credentials. If you don't have an Earthdata Login, you can create one at https://urs.earthdata.nasa.gov//users/new

You can also use pre-existing SLC scenes stored on your Google Drive, or you can copy them using a direct public link from iCloud Drive.

The credentials below are available at the time the notebook is validated.
"""

# Set these variables to None and you will be prompted to enter your username and password below.
#Son variables para guardar mis credenciales
asf_username = 'geri2001'
asf_password = 'Geriborie2001*'

# Acá se crea un objeto ASF para interactuar con el repositorio ASF usando mis credenciales
asf = ASF(asf_username, asf_password)

# Descarga las escenas definidas en la lista SCENES al directorio DATADIR, solo las que
# coinciden con el sub-swath especificado en SUBSWATH.
print(asf.download(DATADIR, BURSTS))

# Este código tiene la función de buscar y descargar las órbitas de los satélites que
# faltan para procesar las escenas Sentinel-1 que ya se han descargado.
S1.download_orbits(DATADIR, S1.scan_slc(DATADIR))

# Este código se encarga de descargar un DEM de Copernicus y mostrarlo como una imagen
Tiles().download_dem(AOI, filename=DEM).plot.imshow(cmap='cividis')

"""## Run Local Dask Cluster

Launch Dask cluster for local and distributed multicore computing. That's possible to process terabyte scale Sentinel-1 SLC datasets on Apple Air 16 GB RAM.
"""

# simple Dask initialization
if 'client' in globals():
    client.close()
client = Client()
client

"""# ¿Por qué se utiliza Dask?

Dask es una librería de Python para computación paralela y distribuida. Permite procesar grandes conjuntos de datos que no caben en la memora RAM de una sola máquina. En este caso, se utiliza Dask para acelerar el procesamiento InSAR, ya que las imágenes Sentinel-1 pueden ser bastante grandes.

### Select Original Scenes and Download DEM and Orbits Later

Use filters to find required subswath, polarization and orbit in original scenes. SAFE directories in the data directory.

# ¿Qué es SBAS?

SBAS significa "Small Baseline Subset" (Conjunto de Líneas Base Pequeñas). Es una técnica usada en InSAR (Interferometría de Radar de Apertura Sintética) que toma varias imágenes de radar (SAR) de un mismo lugar tomadas en diferentes momentos. Luego, selecciona imágenes que estén cerca en tiempo y que tengan pequeñas diferencias de posición entre las órbitas del satélite, para así, combinar estas imágenes para detectar y medir cambios en la superficie del terreno (como deformaciones, subsidencia o movimientos).

El objetivo de SBAS es generar mapas detallados y precisos de cómo se deforma el terreno con el tiempo.
"""

#Se buscan las scenas Sentinel-1 (SLC) dentro del directorio de datos (DATADIR) que
#coincidan con el sub-swath y la polarización espeificada. Esto se guarda en la variable scenes.
scenes = S1.scan_slc(DATADIR, subswath=SUBSWATH)

sbas = Stack(WORKDIR, drop_if_exists=True).set_scenes(scenes).set_reference(REFERENCE)
sbas.to_dataframe()

#Genera un gráfico que muestra la ubicación de las escenas Sentinel-1 en un mapa, utilizando el área de
#interés (AOI) como referencia.

sbas.plot_scenes(AOI=AOI)

"""## Reframe Scenes (Optional)

Stitch sequential scenes and crop the subswath to a smaller area for faster processing when the full area is not needed.

## ¿Qué hace la sección "Reframe Scenes"?

Se encarga de recortar y unir escenas Sentinel-1 para optimizar el procesamiento InSAR. Es un paso opcional pero recomendable, especialmente cuando se trabaja con áreas de interés (AOI) específicas.
"""

## Esta función realiza el corte y la unión (stitching) de las escenas Sentinel-1.

sbas.compute_reframe(AOI)

#genera un gráfico que muestra las escenas recortadas y unidas en un mapa, utilizand el AOI como referencia.

sbas.plot_scenes(AOI=AOI)

"""# Beneficios del "Reframe Scenes"
- Reducción del tiempo de procesamiento: al trabajar con escenas más pequeñas y enfocadas en el área de interés, se reduce la cantidad de datos que se deben procesar, lo que acelera el análisis.
- Menor consumo de memoria: las escenas recortadas ocupan menos espacio en la memoria RAM, lo que permite procesar datasets más grandes en máquinas con recursos limitados.

### Load DEM

The function below loads DEM from file or Xarray variable and converts heights to ellipsoidal model using EGM96 grid.

# ¿Para qué sirve cargar un DEM?

En el procesamiento InSAR, el Modelo Digital de Elevación (DEM) es fundamental para:

- **Corrección topográfica:** el DEM se utiliza para eliminar la influencia del relieve del terreno en las mediciones de deformación.

- **Geocodificación:** el DEM perite transformar las coordenadas de as imágenes SAR a un sistema de coordenadas geográficas.
"""

# Se utilizará el área de interés (AOI) para acelerar el procesamiento al cargar
# solo la porción del DEM que se necesita.
sbas.load_dem(DEM, AOI)

# Este código se encarga de generar un gráfico que muestra la ubicación de las escenas
# Sentinel-1 y luego guardar ese gráfico como una imagen JPG

sbas.plot_scenes(AOI=AOI)

"""# ¿Por qué es útil lo anterior?

Este código es útil para:

- **Visualizar la cobertura geográfica de las escenas:** te permite ver rápidamente qué áreas están cubiertas por las imágenes Sentinel-1 que se utilizarán en el procesamiento InSAR.

- **Verficar la ubicación del AOI:** te ayuda a confirmar que el área de interés está completamente definida y que las escenas las cubren adecuadamente.

- **Documentar el análisis:** guardar el gráfico como una imagen permite tener un registro visual de la ubicación de las escenas, lo cual es útil para la documentación del proyecto.

## Align Images

Esta sección se encarga de alinear las imágenes Sentinel-1 para que estén correctamente superpuestas antes de generar los interferogramas. La alineación precisa es crucial para obtener resultados InSAR de calidad.
"""

# Se utiliza la función copute_align() del objeto sbas (que representa el conjunto de escenas
# para el procesamiento InSAR) para realizar la alineación de las imágenes.
# PyGMTSAR utiliza algoritmos de correlación cruzada para encontrar el desplazamiento entre las
# imágenes y alinearlas con precisión.

sbas.compute_align()

"""# ¿Por qué es necesaria la alineación de imágenes?

Las imágenes Sentinel-1 pueden tener pequeños desplazamientos debido a la geoetría de adquisición, las variaciones en la órbita del satélite y otros factores. Si las imágenes no están correctamente alineadas, los interferogramas resultantes tendrán errores que afectarás la precisión de las mediciones de deformación.

# Geocoding Transform

Este sección se encarga de geocodificar las imágenes Sentinel-1, es decir, transformar las coordenadas de las imágenes desde el sistema de coordenadas del sensor (radar) a un sistema de coordenadas geográficas (latitud y longitud). Este proceso es fundamental para poder visualizar y analizar los resultados InSAR en un contexto geográfico real.
"""

# Se utiliza la configuración predeterminada de PyGMTSAR para la geocodificación,
# que genera una malla de coordenadas geográficas con una resolución de 60 metros.

# PyGMTSAR utiliza la información del DEM y las órbitas de los satélites
# para realizar la transformación de coordenadas. El resultado de la geocodificación es un conjunto
# de imágenes que están georreferenciadas, es decir, que cada pixel de la imagen tiene una ubicación
# geográfica definida.

sbas.compute_geocode(1)

# Este código se encarga de generar un gráfico de la topografía utilizando el DEM
#cargado previamente y luego guardar ese gráfico como una imagen JPG.

sbas.plot_topo(quantile=[0.01, 0.99])

"""# SBAS Baseline

"""

baseline_pairs = sbas.sbas_pairs(days=24)
# optionally, drop dates having less then 2 pairs
#baseline_pairs = sbas.sbas_pairs_limit(baseline_pairs, limit=2, iterations=2)
# Para excluir ciertas fechas específicas (por ejemplo, debido a datos defectuosos o anomalías)
# se debe usar la siguiente línea de código
#baseline_pairs = sbas.sbas_pairs_filter_dates(baseline_pairs, ['2021-01-01'])
baseline_pairs

# Utilizaremos un context manager, el cual permitirá modificar configuraciones de manera temporal,
# de modo que sólo se apliquen dentro de un bloque de código específico y se restauren después de
# ejecutarlo

with mpl_settings({'figure.dpi': 300}):
    sbas.plot_baseline(baseline_pairs)

# dpi (dots per inch): controla la cantidad de píxeles por pulgada en la figura. Un valor de 300
# indica una resulución alta, lo que resulta en una imagen más nítida y detallada.

sbas.compute_ps()
sbas.plot_psfunction(quantile=[0.01, 0.90])

"""## SBAS Analysis

### Multi-looked Resolution for SBAS
"""

# Se toman los pares de imágenes seleccionados y se calculan los interferogramas. Este paso
# ayuda a reducir el ruido den los datos interferométricos

sbas.compute_interferogram_multilook(baseline_pairs, 'intf_mlook', wavelength=30, weight=sbas.psfunction())

# Este código abre el stack intf_mlook y extrae la fase interferométrica (datos
# utilizados para analizar deformaciones en la superficie)
ds_sbas = sbas.open_stack('intf_mlook')
intf_sbas = ds_sbas.phase
corr_sbas = ds_sbas.correlation
corr_sbas

intf_sbas

sbas.plot_interferograms(intf_sbas[:102], caption='SBAS Phase, [rad]')

sbas.plot_correlations(corr_sbas[:102], caption='SBAS Correlation')

"""### 2D Unwrapping"""

unwrap_sbas = sbas.unwrap_snaphu(intf_sbas, corr_sbas)
unwrap_sbas

# Se sincroniza y materializan los datos desenrollados de fase en un archivo
# en disco para facilitar su uso posterior
unwrap_sbas = sbas.sync_cube(unwrap_sbas, 'unwrap_sbas')

sbas.plot_phases(unwrap_sbas.phase[:102], caption='SBAS Phase, [rad]')

"""### Trend Correction"""

decimator = sbas.decimator(resolution=15, grid=(1,1))
topo = decimator(sbas.get_topo())
inc = decimator(sbas.incidence_angle())
yy, xx = xr.broadcast(topo.y, topo.x)
trend_sbas = sbas.regression(unwrap_sbas.phase,
        [topo,    topo*yy,    topo*xx,    topo*yy*xx,
         topo**2, topo**2*yy, topo**2*xx, topo**2*yy*xx,
         topo**3, topo**3*yy, topo**3*xx, topo**3*yy*xx,
         inc,     inc**yy,    inc*xx,     inc*yy*xx,
         yy, xx,
         yy**2, xx**2, yy*xx,
         yy**3, xx**3, yy**2*xx, xx**2*yy], corr_sbas)

# Guarda la tendencia de deformación calculada en un archivo llamado 'trend_sbas'
trend_sbas = sbas.sync_cube(trend_sbas, 'trend_sbas')

sbas.plot_phases(trend_sbas[:102], caption='SBAS Trend Phase, [rad]', quantile=[0.01, 0.99])

sbas.plot_phases((unwrap_sbas.phase - trend_sbas)[:102], caption='SBAS Phase - Trend, [rad]', vmin=-np.pi, vmax=np.pi)

"""### Coherence-Weighted Least-Squares Solution for LOS Displacement, mm"""

# Calcula el desplazamiento a lo largo de la línea de visión (LOS) en milímetros
# a partir de los datos de fase desenrrollada. Recordemos que LOS es la línea
# imaginaria que conecta el satélite con un punto en la superficie terrestre.

disp_sbas = sbas.los_displacement_mm(sbas.lstsq(unwrap_sbas.phase - trend_sbas, corr_sbas))

# Acá se resta la tendencia de fondo, dejando los cambios residuales que realmente reflejan
# la deformación del terreno

# Corresponde al mapa final de desplazamiento LOS en milímetros
disp_sbas = sbas.sync_cube(disp_sbas, 'disp_sbas')

# Genera un mapa que muestra los desplazamientos acumulados en la línea de visión (LOS), medidos en milímetros

sbas.plot_displacements(disp_sbas[::3], caption='SBAS Cumulative LOS Displacement, [mm]', quantile=[0.01, 0.99])

"""### Least-squares model for LOS Displacement, mm"""

velocity_sbas = sbas.velocity(disp_sbas)
velocity_sbas

# optionally, materialize to disk and open
velocity_sbas = sbas.sync_cube(velocity_sbas, 'velocity_sbas')

fig = plt.figure(figsize=(12,4), dpi=300)

zmin, zmax = np.nanquantile(velocity_sbas, [0.01, 0.99])
zminmax = max(abs(zmin), zmax)

ax = fig.add_subplot(1, 2, 1)
velocity_sbas.plot.imshow(cmap='turbo', vmin=-zminmax, vmax=zminmax, ax=ax)
sbas.geocode(AOI.buffer(-BUFFER).boundary).plot(ax=ax)
sbas.geocode(POI).plot(ax=ax, marker='x', c='r', markersize=100, label='POI')
sbas.geocode(POI0).plot(ax=ax, marker='x', c='b', markersize=100, label='POI$\Theta$')
ax.set_aspect('auto')
ax.set_title('Velocity, mm/year', fontsize=16)

ax = fig.add_subplot(1, 2, 2)
sbas.as_geo(sbas.ra2ll(velocity_sbas)).rio.clip(AOI.geometry.buffer(-BUFFER))\
    .plot.imshow(cmap='turbo', vmin=-zminmax, vmax=zminmax, ax=ax)
AOI.buffer(-BUFFER).boundary.plot(ax=ax)
POI.plot(ax=ax, marker='x', c='r', markersize=100, label='POI')
POI0.plot(ax=ax, marker='x', c='b', markersize=100, label='POI$\Theta$')
ax.legend(loc='upper left', fontsize=14)
ax.set_title('Velocity, mm/year', fontsize=16)

plt.suptitle('SBAS LOS Velocity, 2021', fontsize=18)
plt.tight_layout()
plt.show()

"""### STL model for LOS Displacement, mm"""

plt.figure(figsize=(12, 4), dpi=300)

x, y = [(geom.x, geom.y) for geom in sbas.geocode(POI).geometry][0]
disp_pixel = disp_sbas.sel(y=y, x=x, method='nearest')
stl_pixel = sbas.stl(disp_sbas.sel(y=[y], x=[x], method='nearest')).isel(x=0, y=0)
plt.plot(disp_pixel.date, disp_pixel, c='r', lw=2, label='Displacement POI')
plt.plot(stl_pixel.date, stl_pixel.trend, c='r', ls='--', lw=2, label='Trend POI')
plt.plot(stl_pixel.date, stl_pixel.seasonal, c='r', lw=1, label='Seasonal POI')

x, y = [(geom.x, geom.y) for geom in sbas.geocode(POI0).geometry][0]
disp_pixel = disp_sbas.sel(y=y, x=x, method='nearest')
stl_pixel = sbas.stl(disp_sbas.sel(y=[y], x=[x], method='nearest')).isel(x=0, y=0)
plt.plot(disp_pixel.date, disp_pixel, c='b', lw=2, label='Displacement POI$\Theta$')
plt.plot(stl_pixel.date, stl_pixel.trend, c='b', ls='--', lw=2, label='Trend POI$\Theta$')
plt.plot(stl_pixel.date, stl_pixel.seasonal, c='b', lw=1, label='Seasonal POI$\Theta$')

plt.legend(bbox_to_anchor=(1.05, 1), loc='upper left', borderaxespad=0, fontsize=14)
plt.title('SBAS LOS Displacement STL Decompose, 2021', fontsize=18)
plt.ylabel('Displacement, mm', fontsize=16)
plt.show()

"""## 3D Interactive Map"""

velocity_sbas_ll = sbas.ra2ll(velocity_sbas)
# crop to area
velocity_sbas_ll = sbas.as_geo(velocity_sbas_ll).rio.clip(AOI.geometry.buffer(-BUFFER))

# export VTK
sbas.export_vtk(velocity_sbas_ll, 'velocity_sbas', mask='auto')

gmap = XYZTiles().download(velocity_sbas_ll, 15)
gmap.plot.imshow()
sbas.export_vtk(None, 'gmap', image=gmap, mask='auto')

plotter = pv.Plotter(notebook=True)  # Remove shape, as we only have one plot
axes = pv.Axes(show_actor=True, actor_scale=2.0, line_width=5)

vtk_map = pv.read('gmap.vtk').scale([1, 1, 0.00002]).rotate_z(135)

vtk_grid = pv.read('velocity_sbas.vtk').scale([1, 1, 0.00002]).rotate_z(135)
plotter.add_mesh(vtk_map.scale([1, 1, 0.999]), scalars='colors', rgb=True, ambient=0.2)
plotter.add_mesh(vtk_grid, scalars='trend', ambient=0.5, opacity=0.8, cmap='turbo', clim=(-30,30), nan_opacity=0.1, nan_color='black')
plotter.show_axes()
plotter.add_title('SBAS LOS Velocity', font_size=32)

plotter._on_first_render_request()
panel.panel(
    plotter.render_window, orientation_widget=plotter.renderer.axes_enabled,
    enable_keybindings=False, sizing_mode='stretch_width', min_height=600
)

"""## Export VTK file from Google Colab"""

if 'google.colab' in sys.modules:
    from google.colab import files
    files.download('velocity_sbas.vtk')
    files.download('velocity_ps.vtk')

"""## Conclusion"""